multiple linear regression:                                                   
y = w1*x1 + w2*x2 + w3*x3 +..... + b                                          
薪水 = w1*年資 + w2*學歷 + w3*城市 + b                                          

w1, w2, w3?                                                                   
b?

In [1]:
import pandas as pd

data = pd.read_csv("Salary_Data2.csv")
data

    YearsExperience EducationLevel City  Salary
0               3.0             大學  城市A    45.9
1               7.8           碩士以上  城市C    80.5
2               2.3           高中以下  城市A    25.2
3               5.1           高中以下  城市A    30.4
4              10.0           碩士以上  城市B    65.7
5               1.2           碩士以上  城市C    60.8
6               8.6             大學  城市C    50.1
7               6.9           碩士以上  城市A    70.3
8               4.2             大學  城市A    40.7
9               2.4           高中以下  城市A    28.1
10              5.3           高中以下  城市A    32.0
11              3.9             大學  城市A    48.3
12              7.2           碩士以上  城市C    84.2
13             10.0           碩士以上  城市B    70.9
14              1.5           碩士以上  城市C    62.4
15              8.4             大學  城市C    55.6
16              6.5           碩士以上  城市A    72.7
17              4.8             大學  城市A    42.9
18              2.1           高中以下  城市A    26.5
19              5.2           高中以下  城市A    31.6
20              3.5             大學  城市A    43.8
21              7.6           碩士以上  城市C    78.3
22             10.0           碩士以上  城市B    63.6
23              1.8           碩士以上  城市C    58.0
24              8.2             大學  城市C    48.3
25              6.3           碩士以上  城市A    68.4
26              4.6             大學  城市A    38.5
27              2.5           高中以下  城市A    24.9
28              5.0           高中以下  城市A    29.7
29              3.6             大學  城市A    41.6
30              7.4           碩士以上  城市C    76.9
31             10.0           碩士以上  城市B    60.2
32              1.7           碩士以上  城市C    56.3
33              8.0             大學  城市C    45.2
34              6.1           碩士以上  城市A    65.9
35              4.3             大學  城市A    36.7

可根據學歷高低來使用數字代表，但是對於城市民來講，因為不知道高低關係，所以無法用單一代號。                                                                             
＊但是可以使用多個代號，也就是多個特徵＊

In [2]:
data["EducationLevel"] = data["EducationLevel"].map({"高中以下": 0, "大學": 1, "碩士以上": 2})
data

    YearsExperience  EducationLevel City  Salary
0               3.0               1  城市A    45.9
1               7.8               2  城市C    80.5
2               2.3               0  城市A    25.2
3               5.1               0  城市A    30.4
4              10.0               2  城市B    65.7
5               1.2               2  城市C    60.8
6               8.6               1  城市C    50.1
7               6.9               2  城市A    70.3
8               4.2               1  城市A    40.7
9               2.4               0  城市A    28.1
10              5.3               0  城市A    32.0
11              3.9               1  城市A    48.3
12              7.2               2  城市C    84.2
13             10.0               2  城市B    70.9
14              1.5               2  城市C    62.4
15              8.4               1  城市C    55.6
16              6.5               2  城市A    72.7
17              4.8               1  城市A    42.9
18              2.1               0  城市A    26.5
19              5.2               0  城市A    31.6
20              3.5               1  城市A    43.8
21              7.6               2  城市C    78.3
22             10.0               2  城市B    63.6
23              1.8               2  城市C    58.0
24              8.2               1  城市C    48.3
25              6.3               2  城市A    68.4
26              4.6               1  城市A    38.5
27              2.5               0  城市A    24.9
28              5.0               0  城市A    29.7
29              3.6               1  城市A    41.6
30              7.4               2  城市C    76.9
31             10.0               2  城市B    60.2
32              1.7               2  城市C    56.3
33              8.0               1  城市C    45.2
34              6.1               2  城市A    65.9
35              4.3               1  城市A    36.7

In [3]:
from sklearn.preprocessing import OneHotEncoder

onehot_encoder = OneHotEncoder()#因為此套件是一個類別，所以要先做轉換
onehot_encoder.fit(data[['City']])#傳入特徵，由於只接受傳入二維陣列，所以要改變形式
city_encoder = onehot_encoder.transform(data[['City']]).toarray()#開始轉換，並回傳完整的矩陣(因為預設為傳回稀疏矩陣) # type: ignore
city_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [4]:
data[['CityA', 'CityB', 'CityC']] = city_encoder
data.drop(columns=['City', 'CityC'], inplace=True)
data

    YearsExperience  EducationLevel  Salary  CityA  CityB
0               3.0               1    45.9    1.0    0.0
1               7.8               2    80.5    0.0    0.0
2               2.3               0    25.2    1.0    0.0
3               5.1               0    30.4    1.0    0.0
4              10.0               2    65.7    0.0    1.0
5               1.2               2    60.8    0.0    0.0
6               8.6               1    50.1    0.0    0.0
7               6.9               2    70.3    1.0    0.0
8               4.2               1    40.7    1.0    0.0
9               2.4               0    28.1    1.0    0.0
10              5.3               0    32.0    1.0    0.0
11              3.9               1    48.3    1.0    0.0
12              7.2               2    84.2    0.0    0.0
13             10.0               2    70.9    0.0    1.0
14              1.5               2    62.4    0.0    0.0
15              8.4               1    55.6    0.0    0.0
16              6.5               2    72.7    1.0    0.0
17              4.8               1    42.9    1.0    0.0
18              2.1               0    26.5    1.0    0.0
19              5.2               0    31.6    1.0    0.0
20              3.5               1    43.8    1.0    0.0
21              7.6               2    78.3    0.0    0.0
22             10.0               2    63.6    0.0    1.0
23              1.8               2    58.0    0.0    0.0
24              8.2               1    48.3    0.0    0.0
25              6.3               2    68.4    1.0    0.0
26              4.6               1    38.5    1.0    0.0
27              2.5               0    24.9    1.0    0.0
28              5.0               0    29.7    1.0    0.0
29              3.6               1    41.6    1.0    0.0
30              7.4               2    76.9    0.0    0.0
31             10.0               2    60.2    0.0    1.0
32              1.7               2    56.3    0.0    0.0
33              8.0               1    45.2    0.0    0.0
34              6.1               2    65.9    1.0    0.0
35              4.3               1    36.7    1.0    0.0

In [5]:
from sklearn.model_selection import train_test_split

x = data.loc[:, ['YearsExperience', 'EducationLevel', 'CityA', 'CityB']]
y = data.loc[:, ['Salary']]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=87)#random_state可以固定分割的資料，確保不會一直變動

x_train = x_train.to_numpy()
x_test = x_test.to_numpy()

改寫後變成有4個W                                                                  
w1, w2, w3, w4?                                                                  
b?

In [6]:
import numpy as np

w = np.array([1, 2, 3, 4])
b = 1
y_predict = (x_train * w).sum(axis=1) + b
#如果axis等於1的話那就是進行每行的加總，如果等於0的話就是進行每列的加總
y_predict

array([ 9.6, 14.3, 10.8, 12.2, 19. ,  6.8,  6.1,  9.9, 12.6, 19. , 11.2,
        9.1, 19. , 10.2,  9.3,  6.5, 12.4,  9. ,  6.4,  9. ,  9.2, 11. ,
       11.6, 11.4, 19. ])

In [7]:
y_train = y_train.to_numpy()

((y_train - y_predict)**2).mean()#計算平均

1895.75544

In [8]:
def compute_cost(x, y, w, b):
    '''
    returns:
    cost is corresponding w and b

    Parameters:
    x, y(training data)
    w, b(a array of weight, a constant of bias)
    '''
    y_predict = (x * w).sum(axis=1) + b
    cost = ((y - y_predict)**2).mean()

    return cost

In [9]:
w = np.array([0, 2, 2, 4])
b = 0
compute_cost(x_train, y_train, w, b)

2538.4628

Gradient descent就是根據斜率改變參數(w1, w2, w3, w4, b)                           
1.可以透過微分的方式計算出一個點的切線斜率。                                      
如何計算出斜率?                                                                 
    先設定好cost function長什麼樣子，這邊的cost function就是(y - y_pred)**2      
    =(y - (w1*x1 + w2*x2 + w3*x3 + w4 * x4 + b))**2                              
    w1微分 = 2 * x1(y_predict - y)                                               
    W2微分 = 2 * x2(y_predict - y)                                               
    W3微分 = 2 * x3(y_predict - y)                                               
    W4微分 = 2 * x4(y_predict - y)                                               
    b微分 = 2(y_predict - y)                                                   
2.接著開始更新w以及b                                                            
    w1 - w1方向斜率 * 學習率                                                      
    w2 - w2方向斜率 * 學習率                                                      
    w3 - w3方向斜率 * 學習率                                                      
    w4 - w4方向斜率 * 學習率                                                      
    b - b方向斜率 * 學習率                                                        
3.接著一直重複更新w以及b知道找到最低的cost為止

In [10]:
y_predict = (x_train * w).sum(axis=1) + b
b_gradient = (y_predict - y_train).mean()

w_gradient = np.zeros(x_train.shape[1])
for i in range(x_train.shape[1]):
    w_gradient[i] = (x_train[:, i] * (y_predict - y_train)).mean()

w_gradient, b_gradient

(array([-281.52128,  -53.8872 ,  -23.1616 ,   -6.9472 ]), -47.5)

In [11]:
def compute_gradient(x, y, w, b):
    '''
    Returns:
    w_gradient(微分結果, a array), b_gradient(微分結果)
    
    Parameters:
    x, y(data)
    w, b(a array of weight, a constant of bias)
    '''
    y_predict = (x * w).sum(axis=1) + b
    b_gradient = (y_predict - y).mean()

    w_gradient = np.zeros(x.shape[1])
    for i in range(x.shape[1]):
        w_gradient[i] = (x[:, i] * (y_predict - y)).mean()

    return w_gradient, b_gradient

In [12]:
w = np.array([1, 2, 2, 4])
b = 1
learning_rate = 0.001

w_gradient, b_gradient = compute_gradient(x_train, y_train, w, b)

print(compute_cost(x_train, y_train, w, b))

w = w - w_gradient * learning_rate
b = b - b_gradient * learning_rate
print(compute_cost(x_train, y_train, w, b))
print(w, b)

1936.5666400000002
1823.0109787829138
[1.23235888 2.0448752  2.0206456  4.0051872 ] 1.040516

In [13]:
np.set_printoptions(formatter={'float': '{: .2e}'.format})
#需要轉換格式因為w以及w_gradient是一個陣列形態
def gradient_descent(x, y, w_init, b_init, learning_rate, cost_function, gradient_function, run_iter, p_iter=1000):
    
    c_hist = []
    w_hist = []
    b_hist = []
    
    w = w_init
    b = b_init

    for i in range(run_iter + 1):
        w_gradient, b_gradient = gradient_function(x, y, w, b)

        w = w - w_gradient*learning_rate
        b = b - b_gradient*learning_rate
        cost = cost_function(x, y, w, b)

        w_hist.append(w)
        b_hist.append(b)
        c_hist.append(cost)

        if i%p_iter == 0:
            print(f"Iteration {i:5} : Cost {cost: .4e}, w: {w}, b: {b: .2e}, w_gradient: {w_gradient}, b_gradient: {b_gradient: .2e}")

    return w, b, w_hist, b_hist, c_hist

In [14]:
w_init = np.array([1, 2, 2, 4])
b_init = 0
learning_rate = 1.0e-2
run_iter = 20000
p_iter = 2000

w_final, b_final, w_hist, b_hist, c_hist = gradient_descent(x_train, y_train, w_init, b_init, learning_rate, compute_cost, compute_gradient, run_iter, p_iter)

Iteration     0 : Cost  1.0741e+03, w: [ 3.38e+00  2.46e+00  2.21e+00  4.05e+00], b:  4.15e-01, w_gradient: [-2.38e+02 -4.60e+01 -2.11e+01 -5.35e+00], b_gradient: -4.15e+01
Iteration  2000 : Cost  2.9464e+02, w: [ 1.66e+00  5.63e+00  1.24e+01 -5.95e+00], b:  2.94e+01, w_gradient: [ 3.38e-02  1.35e-01  3.35e-01 -8.76e-03], b_gradient: -5.34e-01
Iteration  4000 : Cost  2.8434e+02, w: [ 1.08e+00  3.50e+00  7.41e+00 -4.68e+00], b:  3.78e+01, w_gradient: [ 2.42e-02  8.24e-02  1.81e-01 -8.47e-02], b_gradient: -3.22e-01
Iteration  6000 : Cost  2.8043e+02, w: [ 6.85e-01  2.19e+00  4.59e+00 -3.12e+00], b:  4.29e+01, w_gradient: [ 1.58e-02  5.12e-02  1.08e-01 -6.79e-02], b_gradient: -2.00e-01
Iteration  8000 : Cost  2.7890e+02, w: [ 4.32e-01  1.38e+00  2.87e+00 -1.99e+00], b:  4.61e+01, w_gradient: [ 1.00e-02  3.20e-02  6.70e-02 -4.54e-02], b_gradient: -1.25e-01
Iteration 10000 : Cost  2.7829e+02, w: [ 2.71e-01  8.63e-01  1.80e+00 -1.26e+00], b:  4.81e+01, w_gradient: [ 6.31e-03  2.01e-02  4.19e-02 -2.91e-02], b_gradient: -7.83e-02
Iteration 12000 : Cost  2.7805e+02, w: [ 1.70e-01  5.42e-01  1.13e+00 -7.90e-01], b:  4.93e+01, w_gradient: [ 3.96e-03  1.26e-02  2.63e-02 -1.83e-02], b_gradient: -4.92e-02
Iteration 14000 : Cost  2.7796e+02, w: [ 1.07e-01  3.41e-01  7.09e-01 -4.96e-01], b:  5.01e+01, w_gradient: [ 2.49e-03  7.92e-03  1.65e-02 -1.15e-02], b_gradient: -3.09e-02
Iteration 16000 : Cost  2.7792e+02, w: [ 6.72e-02  2.14e-01  4.45e-01 -3.12e-01], b:  5.06e+01, w_gradient: [ 1.56e-03  4.97e-03  1.04e-02 -7.25e-03], b_gradient: -1.94e-02
Iteration 18000 : Cost  2.7791e+02, w: [ 4.22e-02  1.34e-01  2.80e-01 -1.96e-01], b:  5.09e+01, w_gradient: [ 9.82e-04  3.12e-03  6.51e-03 -4.55e-03], b_gradient: -1.22e-02
Iteration 20000 : Cost  2.7790e+02, w: [ 2.65e-02  8.44e-02  1.76e-01 -1.23e-01], b:  5.11e+01, w_gradient: [ 6.17e-04  1.96e-03  4.09e-03 -2.86e-03], b_gradient: -7.65e-03

In [15]:
from sklearn.linear_model import LinearRegression

regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

### 使用 pandas.concat() 方法將兩個 Pandas 系列合併為一個 DataFrame

In [16]:
y_predict = regressor.predict(x_test)

In [17]:
y_predict = pd.DataFrame(y_predict)

y_predict_and_y_test = pd.concat([y_test, y_predict], axis=1)
new_columns = ['y test', 'y predict']
y_predict_and_y_test.columns = new_columns
y_predict_and_y_test

    y test  y predict
20    43.8        NaN
16    72.7        NaN
5     60.8  23.939209
27    24.9        NaN
32    56.3        NaN
2     25.2  61.798896
1     80.5  70.818719
7     70.3  71.504821
26    38.5        NaN
35    36.7        NaN
34    65.9        NaN
0      NaN  45.835233
3      NaN  24.282260
4      NaN  62.656525
6      NaN  73.119591
8      NaN  47.722015
9      NaN  47.207438
10     NaN  70.132616

In [18]:
w_final, b_final

(array([ 2.65e-02,  8.44e-02,  1.76e-01, -1.23e-01]), 51.091110689905385)

In [19]:
y_predict = (x_test * w_final).sum(axis=1) + b_final

In [20]:
y_test = y_test.to_numpy()
compute_cost(x_test, y_test, w_final, b_final)

346.2247940672084

In [21]:
from sklearn import metrics
print(f"Mean Squared Error: {metrics.mean_squared_error(y_test, y_predict)}")

Mean Squared Error: 343.89485716156975

套用到真實情況

In [22]:
# 5.3 碩士以上 城市A
# 7.2 高中以下 城市B
x_real = np.array([[5.3, 2, 1, 0], [7.2, 0, 0, 1]])
y_real = (w_final*x_real).sum(axis=1) + b_final
y_real

array([ 5.16e+01,  5.12e+01])